- feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecNode.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
- Take into account passive and optional expressed in read-feature-descriptions
- Do not take into account optional module dependencies present in module.xml
- Split bin packages into "tools" packages.
> Changes to allow for reduced provisioned content

- maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser31.java
Introduce urn:wildfly:feature-pack-build:3.1 which allows to add translate-to-fpl=true|false to feature-pack dependencies indicating whether the location of the dependency should be stored in the Galleon FPL or the Maven GAV format. With Maven GAV being the default format, which is different from the previous versions of WildFly Galleon Plugins.
> [WFGP-163] translate-to-fpl for feature-pack dependencies

- feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecGenerator.java
- feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecNode.java
* When adding new feature-ids at spec generation, doing it recursively so that it can be referenced properly from all descendants.
Jira: https://issues.redhat.com/browse/WFGP-170
> [WFGP-170]: Can't provision features generated only for standalone.

- maven-plugin/src/main/java/org/wildfly/galleon/maven/AllArtifactListGeneratorMojo.java
Issue: https://issues.redhat.com/browse/WFGP-185
> Fix for WFGP-185, Maven goal generate-all-artifacts-list ignores classifier for extra-artifacts

- maven-plugin/src/main/java/org/wildfly/galleon/maven/AllArtifactListGeneratorMojo.java
Issue: https://issues.redhat.com/browse/WFGP-185
> [5.x] Fix for WFGP-185, Maven goal generate-all-artifacts-list ignores classifier for extra-artifacts

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java
- pom.xml
- transformer/src/main/java/org/wildfly/galleon/plugin/transformer/JakartaTransformer.java
Issues:
* https://issues.redhat.com/projects/WFGP/issues/WFGP-179
* https://issues.redhat.com/projects/WFGP/issues/WFGP-183
* https://issues.redhat.com/projects/WFGP/issues/WFGP-186
* Package a file inside f-p containing the list of artifacts that don't require transformation during provisioning.
* Ability to disable transformation by relying on a "provisioning local maven repo".
* Slim server provisioning, proper handling of local maven cache.
* Ability to enable traces in transformer Main entry point and during provisioning.
* Upgrade to batavia 1.0.1
@bstansberry , I am adding some documentation on what happens in the various provisioning scenarii.
Fat server with transformation
* During module transformation, populate transformationMavenRepo for example configs to avoid re-transform. …
> WFGP-179, WFGP-183 and WFGP-186

- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java
https://issues.redhat.com/browse/WFGP-187
> [WFLY-187] Properly quote the file separator passed to String.replaceAll

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java
Issue: https://issues.redhat.com/browse/WFGP-188
@bstansberry that is the renaming feature.
Add suffix to FP configuration.
Use suffix for transformed artifact. 
Fat server: Update artifact name and module.xml.
Thin server: Update module.xml artifacts GAV, locate renamed artifact in a version directory containing the suffix.
Feature-spec generation is done based on non re-named artifacts (this is an internal provisioning). The generated maven repository (that can be used as a cache to provision servers without the need to transform artifacts in later steps) contains the  renamed artifact.
> Fix for WFGP-188, Rename jakarta transformed artifacts

- galleon-plugins/pom.xml
- pom.xml
New version of XOM doesn't access to JDK internal classes.
* Upgraded XOM dependency (groupid changed).
* Removed xml-apis that is no more a dependency.
> Fix for WFGP-195, Can't provision WildFly using JDK 16.

- pom.xml
Brings in fixes:
* [BATAVIA-101] Transform the legacy JAXB NS to the EE9
https://issues.redhat.com/browse/WFGP-202
Upstream: #199
> [WFGP-202] Upgrade Batavia to 1.0.8.Final

- feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecNode.java
* Fixing this by transforming the domain packages description as a Set instead of a List to compare it properly with the Set from
standalone.
Jira: https://issues.redhat.com/browse/WFGP-199
> [WFGP-199]: Useless error: org.jboss.galleon.ProvisioningException:Packages dependencies don't match.

- maven-plugin/src/main/java/org/wildfly/galleon/maven/WildFlyFeaturePackBuild.java
Issue: https://issues.redhat.com/browse/WFGP-205
> Fix for WFGP-205, Dependency order in wildfly-feature-pack-build is not preserved

- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java
https://issues.redhat.com/browse/WFGP-207
> [WFGP-207] Do not add a "security-realm" reference in the initial config.

- maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/JakartaTransformation.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenProjectArtifactVersions.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/UserFeaturePackBuildMojo.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
* Transformation can occur for FP dependencies when no extension is present.
* Transformation also applies to UserFeaturePackBuildMojo
* Generation of excluded artifacts occurs in all cases (if transformation is enabled).
> Fix for WFGP-208, Generation of wildfly-jakarta-transform-excludes.txt is bound to feature-spec generation

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/Utils.java
- galleon-plugins/src/test/java/org/wildfly/galleon/plugin/UtilsTestCase.java
* Fixing the way versions are resolved so that the full GAV (with classifier and extension) is taken into account.
Jira: https://issues.redhat.com/browse/WFGP-214
> Fixing the way versions are resolved so that the full GAV (with classifier and extension) is taken into account.

- maven-plugin/src/main/java/org/wildfly/galleon/maven/JakartaTransformation.java
Issue: https://issues.redhat.com/browse/WFGP-220
> Fix for WFGP-220, jakarta-transform-excluded-artifacts must be copied to local cache

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractModuleTemplateProcessor.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/FatModuleTemplateProcessor.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ThinModuleTemplateProcessor.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/Utils.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
- galleon-plugins/src/test/java/org/wildfly/galleon/plugin/UtilsTestCase.java
- pom.xml
* Detect that the Maven resolver is using WildFly channels
* When channel are enabled, ignore unresolved expressions for artifact Version
* Bump galleon to 5.0.1.Final
> Fix for WFGP-223, Ignore Unresolved version expression when using WildFly channel

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractModuleTemplateProcessor.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
- pom.xml
Issue: https://issues.redhat.com/browse/WFGP-230
If 'bulk-resolve-artifacts' option is specified, module templates are scanned before being processing to build a list of required artifacts.
All the required artifacts are then resolved in a single Maven operation rather then individual requests.
Note: depends on Galleon API change https://github.com/wildfly/galleon/pull/305
Note 2: related channels change: https://github.com/wildfly-extras/wildfly-channel/pull/75
> [WFGP-230] Using resolveAll to resolve jboss modules

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WildFlyPackageTasks.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/LineEndingsTask.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser20.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser31.java
- maven-plugin/src/main/resources/schema/wildfly-feature-pack-tasks-3_1.xsd
Issue: https://issues.redhat.com/browse/WFGP-232
This would allow to run the line-ending filter after FINALIZING phase tasks like this:
```
<tasks xmlns="urn:wildfly:wildfly-feature-pack-tasks:3.1">
<delete path="docs/licenses/licenses.html"/>
<xml-merge basedir="docs/licenses" output="docs/licenses/licenses.xml">
<filter pattern="*-licenses.xml" include="true"/>
</xml-merge>
<transform stylesheet="docs/licenses/licenses.xsl" src="docs/licenses/licenses.xml" output="docs/licenses/licenses.html" phase="FINALIZING"/>
<line-endings phase="FINALIZING">
<unix>
<filter pattern="docs/licenses/licenses.html" include="true"/>
</unix>
</line-endings>
</tasks>
```
> [WFGP-232] Add phase attribute to line-ending filter

- maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleXmlParser.java
- maven-plugin/src/test/java/org/wildfly/galleon/maven/ModuleAliasTestCase.java
Issue: https://issues.redhat.com/browse/WFGP-233
In addition to the fix, the parsing of module name that contain the slot has been extended to cover all JBoss Module modules names.
>  Fix for WFGP-233, JBoss Modules aliases are not provisioned when Galleon provisions the target module

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffPlugin.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-243
The config-gen jar is now retrieved from maven, as any other maven artifact required by the galleon-plugins.
> Fix for WFGP-243, config-gen jar shouldn't be packaged in the feature-pack

- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigGenerator.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/MonitorableArtifact.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-245
Adding two new trackers to the WfInstallPlugin to provide updates on bulk resolving artifacts and hide generating 2nd server to create examples.
@jfdenise l I'm not sure if that's a correct way to use the ProgressTrackers, could you take a look at this when you have a moment?
> [WFGP-245] improve progress tracking

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/MonitorableArtifact.java
Issue: https://issues.redhat.com/browse/WFGP-245
Update for #248 - need to call processing before processed to make the item available in callback
> [WFGP-245] Correctly set resolved artifact in ProgressTracker

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/MonitorableArtifact.java
The MavenArtifacts are wrapped in MonitorableArtifacts before being resolved. The Metadata needs to be exposed in MonitorableArtifacts to allow the resolver to determine if channels are needed.
issue: https://issues.redhat.com/browse/WFGP-250](https://issues.redhat.com/browse/WFGP-250
> [WFGP-250] Include the artifact metadata when wrapping artifacts

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/XmlMerge.java
Issue: https://issues.redhat.com/browse/WFGP-253
Convert file paths to URIs before passing them into XSL to escape special characters. XSL document() function extects the argument to be URI
> [WFGP-253] Use URIs instead of file paths when setting up XmlMerge

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ArtifactRecorder.java
Issue: https://issues.redhat.com/browse/WFGP-257
> [WFGP-257] Use linux path separator in artifact cache record

- config-gen/pom.xml
- docs/guide/examples/user-defined-feature-pack/content.adoc
- docs/guide/maven-plugins/index.adoc
- docs/pom.xml
- feature-spec-gen/pom.xml
- galleon-plugins/pom.xml
- maven-plugin/pom.xml
- maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
- pom.xml
- transformer/pom.xml
WildFly tests are expected to fail, would require a bump of provisioning tooling.
> Version 7.x depends on Galleon 6.x, enforce Layer check at build time

- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/BaseConfigGenerator.java
- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigGenerator.java
- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfProvisionedConfigHandler.java
- feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecGenerator.java
- feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecNode.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleParseResult.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleXmlParser.java
- maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
- pom.xml
Issues:
https://issues.redhat.com/browse/WFGP-264
https://issues.redhat.com/browse/WFGP-265
https://issues.redhat.com/browse/WFGP-272
> Fix for WFGP-264, WFGP-265 and WFGP-272, stability handling

- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-276
Upstream: #286
> [WFGP-276] Check if the artifact is a ZIP or a JAR archive before extracting schemas

- maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
- pom.xml
Issue: https://issues.redhat.com/browse/WFGP-279
> Fix for WFGP-279, Enforce that minimum stability enables the specified stability

- docs/guide/intro/index.adoc
This PR fixes a wrong Maven group ID in the documentation: `org.wildfly.galleon` → `org.wildfly.galleon-plugins`
> Fix wrong group id in documentation

- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/BaseConfigGenerator.java
- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/ForkedConfigGenerator.java
- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/ServerBridge.java
- config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfProvisionedConfigHandler.java
- galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Isolated execution of Embedded Server during provisioning.
* Config generation is operated from 2 classloaders. First one load the config generator + CLI (DMR, ...). This one delegates to the context classloader. That is OK, no embedded server part.
*  The second one only load the embedded server + all its dependencies (such as DMR all from cli:client) + JBoss Modules
So DMR is loaded twice. In the first classloader, converted to yaml String to be consumed on the embedded side.
This isolation should be even more strict than the forked process approach.
> Fix for WFGP-284, Embedded server execution should be isolated in its own classloader
