wildfly/galleon-plugins

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfCliPlugin.java, galleon-plugins/src/main/resources/META-INF/services/org.jboss.galleon.plugin.CliPlugin
WF CLI plugin to handle custom content (modules).
=> WFCliPlugin to handle custom content, modules for now)

pom.xml
https://issues.jboss.org/browse/WFGP-19
=> [WFGP-19] Upgrade to jboss-modules 1.8.5.Final

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigGenerator.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfProvisionedConfigHandler.java, feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecDescriptionReader.java, feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugins/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java, maven-plugins/src/main/java/org/wildfly/galleon/maven/WfFeatureSpecBuildMojo.java
https://issues.jboss.org/browse/WFGP-21
=> [WFGP-21] Add an option to run the embedded task in a separate process

feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ForkedEmbeddedUtil.java, maven-plugins/src/main/java/org/wildfly/galleon/maven/WfFeatureSpecBuildMojo.java
https://issues.jboss.org/browse/WFGP-25
=> WFGP-25 Do not override the default Java system properties for the forked embedded process

docs/guide/maven-plugins/goals/build-feature-pack/index.adoc, docs/guide/maven-plugins/goals/build-feature-pack/jboss-module-packages/index.adoc, docs/guide/maven-plugins/goals/build-feature-pack/non-module-packages/index.adoc, maven-plugins/src/main/java/org/wildfly/galleon/maven/WfFeatureSpecBuildMojo.java
https://issues.jboss.org/browse/WFGP-26
=> WFGP-26 Remove the temporary directory for the feature spec generating dist

pom.xml
https://issues.jboss.org/browse/WFGP-28
=> [WFGP-28] Upgrade to Galleon 1.0.0.Final

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WildFlyPackageTasks.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/FilePermissions.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser20.java
https://issues.jboss.org/browse/WFGP-32
=> [WFGP-32] Turn file permissions processing into a separate package task

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ForkedEmbeddedUtil.java
An Exception thrown from the main method of the forked process is not correctly read by the caller which hangs waiting for a response.
Jira issue: https://issues.jboss.org/browse/WFGP-35
=> [WFGP-35] Provisioning hangs when a batch operation fails

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffConfigGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffResult.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugins/pom.xml, maven-plugins/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser.java, maven-plugins/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser30.java, maven-plugins/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, maven-plugins/src/main/java/org/wildfly/galleon/maven/WildFlyFeaturePackBuild.java, pom.xml
https://issues.jboss.org/browse/WFGP-39
=> [WFGP-39] Upgrade to Galleon 2.0.0.Alpha1

maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
https://issues.jboss.org/browse/WFGP-37
=> [WFGP-37] Fix/update JavaDoc of WfFeaturePackBuildMojo

pom.xml
https://issues.jboss.org/browse/WFGP-41
=> [WFGP-41] Upgrade the dependency to WildFly Core to 5.0.0.Final

pom.xml
https://issues.jboss.org/browse/WFGP-42
=> [WFGP-42] Upgrade to Galleon 2.0.0.Alpha2

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfProvisionedConfigHandler.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser30.java, pom.xml
https://issues.jboss.org/browse/WFGP-43
https://issues.jboss.org/browse/WFGP-44
=> [WFGP-43], [WFGP-44] Support provisioning customized transitive dependencies

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
https://issues.jboss.org/browse/WFGP-47
=> [WFGP-47] more verbose info for WfInstallPlugin

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffConfigGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfUpgradePlugin.java, pom.xml
https://issues.jboss.org/browse/WFGP-49
https://issues.jboss.org/browse/WFGP-50
=> WFGP-49, WFGP-50 Progress tracking

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
https://issues.jboss.org/browse/WFGP-52
=> [WFGP-52] Remove default progress tracker for installation of packages

maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
@aloubyansky could you please review?
=> [WFGP-51] Make WfFeaturePackBuildMojo.releaseName optional

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
https://issues.jboss.org/browse/WFGP-54
=> [WFGP-54] Support extension and classifier in copy-artifact package task

pom.xml
https://issues.jboss.org/browse/WFGP-55
=> [WFGP-55] upgrade jboss-parent to 28

maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
@aloubyansky could you please review?
https://issues.jboss.org/browse/WFGP-56
=> [WFGP-56] resourcesDir must not get prefixed with /

maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenProjectArtifactVersions.java
changes in MavenProjectArtifactVersions.versions
https://issues.jboss.org/browse/WFGP-57
@aloubyansky could you please review?
=> [WFGP-57] Replace HashMap with TreeMap for better traceability of

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/CompleteServer.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/CompleteServerInvoker.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/ScriptRunner.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigsReader.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfDiffConfigGenerator.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfEmbeddedTaskBase.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfProvisionedStateDiff.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfScriptExecutor.java, galleon-plugins/pom.xml, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/Utils.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffResult.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfUpgradePlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfUserConfigDiffPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/CopyArtifact.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser20.java, galleon-plugins/src/main/resources/META-INF/services/org.jboss.galleon.plugin.UserConfigDiffPlugin, pom.xml
https://issues.jboss.org/browse/WFGP-58
https://issues.jboss.org/browse/WFGP-62
https://issues.jboss.org/browse/WFGP-63
=> WFGP-58, WFGP-62, WFGP-63, experimental config diffs

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser20.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/XslTransform.java
https://issues.jboss.org/browse/WFGP-69
https://issues.jboss.org/browse/WFGP-70
=> [WFGP-69] [WFGP-70] XSL Transform task phase and properties

maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeatureSpecBuildMojo.java
=> [WFGP-71] WfFeatureSpecBuildMojo.domainExtensions and hostExtensions

maven-plugin/pom.xml
@aloubyansky could you please review?
=> [WFGP-77] Define goalPrefix of maven-plugin-plugin

pom.xml
https://issues.jboss.org/browse/WFGP-92
=> [WFGP-92] Upgrade to Galleon 2.0.1.Final

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfDiffPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleParseResult.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleXmlParser.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, pom.xml
https://issues.jboss.org/browse/WFGP-98
https://issues.jboss.org/browse/WFGP-99
=> [WFGP-99] [WFGP-98] Add support for generating passive package dependencies

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/DeletePath.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser20.java
https://issues.jboss.org/browse/WFGP-100
=> [WFGP-100] support if-empty attribute for delete-path task

pom.xml
Update license name in pom file to "Apache License 2.0" to match name in https://spdx.org/licenses/
=> Update license name in pom file to match name in https://spdx.org/licenses

pom.xml
https://issues.jboss.org/browse/WFGP-101
=> [WFGP-101] Upgrade to Galleon 3.0.0.Alpha4

maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenProjectArtifactVersions.java
https://issues.jboss.org/browse/WFGP-108
=> [WFGP-108] Exclude test-jar artifacts from artifact-versions.properties

pom.xml
https://issues.jboss.org/browse/GAL-224
=> [WFGP-224] upgrade to Galleon 3.0.0.Final

pom.xml
https://issues.jboss.org/browse/WFGP-110
=> [WFGP-110] upgrade to latest jboss-parent

docs/guide/maven-plugins/goals/index.adoc
https://issues.jboss.org/browse/WFGP-112
=> [WFGP-112] update the docs

pom.xml
https://issues.jboss.org/browse/WFGP-115
=> [WFGP-115] Upgrade to Galleon 3.0.1.Alpha1

pom.xml
https://issues.jboss.org/browse/WFGP-123
=> [WFGP-123] Upgrade to Galleon 3.0.1.CR2

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser30.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WildFlyFeaturePackBuild.java, pom.xml
https://issues.jboss.org/browse/WFGP-125
https://issues.jboss.org/browse/WFGP-126
=> [WFGP-125] [WFGP-126]

maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser20.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser30.java, pom.xml
https://issues.jboss.org/browse/WFGP-127
=> [WFGP-127] upgrade to Galleon 3.0.1.Final

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
https://issues.jboss.org/browse/WFGP-128
=> [WFGP-128] NoSuchFileException with inherit-configs false

pom.xml
https://issues.jboss.org/browse/WFGP-133
=> [3.x][WFGP-133] Use https URLs in pom repository configuration

pom.xml
https://issues.jboss.org/browse/WFGP-133
=> [WFGP-133] Use https URLs in pom repository configuration

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigsReader.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenProjectArtifactVersions.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenRepoBuilder.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenRepositoryGeneratorMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleXmlVersionResolver.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/UserFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/Util.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/build/tasks/CopyResourcesTask.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/build/tasks/ResourcesTask.java, pom.xml
- Fix for WFGP-130, Tooling for end user creation of Galleon feature packs
- Fix for WFGP-134, Generate all-artifacts.properties file
- Fix for WFGP-132, Add the ability to generate a maven repo from a feature-pack
=> Various fixes required by WildFly

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/AllArtifactListGeneratorMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ArtifactListBuilder.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ArtifactListMerger.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenRepoBuilder.java, pom.xml
- Generate and deploy offliner file.
- Plugin to aggregate offliners.
=> Fix for WFGP-135, plugins to generate and deploy FP offliner file and  offliner aggregation

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
=> Fix for WFGP-136, Warn when a user defined package.xml overwrite a generated package.xml

maven-plugin/src/main/java/org/wildfly/galleon/maven/ArtifactListBuilder.java
=> Fix for WFGP-137, checksum formatting doesn't work on jdk 11

pom.xml
https://issues.jboss.org/browse/WFGP-139
=> [WFGP-139] Upgrade to Galleon 4.0.0.Beta1

pom.xml
https://issues.jboss.org/browse/WFGP-140
=> [WFGP-140] Upgrade to Galleon 4.0.0.Final

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/UserFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/Util.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
Handle add-ons when packaging modules.
=> Fix for WFGP-147, Allow to package module as add-ons

docs/scripts/assembly-docs.xml, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/FileAppender.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser30.java
Appending lines to a file during installation. Those lines can be
defined in a sequence of <line> tags or in a file.
Jira: https://issues.jboss.org/browse/WFGP-146
=> [WFGP-146]: Add support for appending content to files

docs/guide/maven-plugins/goals/build-feature-pack/jboss-module-packages/index.adoc, docs/guide/maven-plugins/goals/build-user-feature-pack/configs/index.adoc, docs/guide/maven-plugins/goals/build-user-feature-pack/feature-groups/index.adoc, docs/guide/maven-plugins/goals/build-user-feature-pack/index.adoc, docs/guide/maven-plugins/goals/build-user-feature-pack/jboss-module-packages/index.adoc, docs/guide/maven-plugins/goals/build-user-feature-pack/layers/index.adoc, docs/guide/maven-plugins/goals/build-user-feature-pack/packages/index.adoc, docs/guide/maven-plugins/goals/build-user-feature-pack/user-fp-build-xml/index.adoc, docs/guide/maven-plugins/wildfly-feature-pack-build-xml/index.adoc, maven-plugin/src/main/java/org/wildfly/galleon/maven/UserFeaturePackBuildMojo.java
Evolved documentation.
Fixes WFGP-152
=> Fix for WFGP-152, Tooling for end user creation of Galleon feature packs

.travis.yml, pom.xml
=> WFGP-153 Upgrade to Galleon 4.0.4.Final

pom.xml
https://issues.jboss.org/browse/WFGP-155
=> [WFGP-155] Upgrade to Galleon 4.1.0.Final

docs/guide/maven-plugins/wildfly-feature-pack-build-xml/index.adoc
=> Fix for WFGP-157, Wrong wildfly-user-feature-pack-build.xml example in documention

pom.xml
https://issues.jboss.org/browse/WFGP-159
=> [WFGP-159] Upgrade to Galleon 4.2.0.Final

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/AllArtifactListGeneratorMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ArtifactListBuilder.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ArtifactListMerger.java
* Added extra artifacts configuration parameter.
* Log added artifacts.
=> Fix for WFGP-158, Add extra GAV to the generated offliner file

maven-plugin/src/main/java/org/wildfly/galleon/maven/AllArtifactListGeneratorMojo.java
Issue: https://issues.jboss.org/browse/WFGP-162
=> Fix for WFGP-162, NPE when no extra artifacts are provided

maven-plugin/pom.xml, maven-plugin/src/main/java/org/wildfly/galleon/maven/AllArtifactListGeneratorMojo.java, pom.xml
Issue: https://issues.jboss.org/browse/WFGP-164
=> Fix for WFGP-164, Generate licenses.xml for artifacts contained in generated offliner

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
Issues: 
https://issues.redhat.com/browse/WFGP-171
https://issues.redhat.com/browse/WFGP-173
https://issues.redhat.com/browse/WFGP-174
https://issues.redhat.com/browse/WFGP-175
=> Various plugins and maven plugin fixes

maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser32.java
Issue: https://issues.redhat.com/browse/WFGP-176
Introduced new parser version to support list of patches.
=> Fix for WFGP-176, Allow to use patches in fp builder xml file

maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
Create a package named bin.jdrtools to add the JDR specific scripts.
Jira issue: https://issues.redhat.com/browse/WFGP-177
=> [WFGP-177] Generate a package for the JBoss Diagnostic Reporting scripts

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugin/pom.xml, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
https://issues.redhat.com/browse/WFGP-180
Also includes the commit from #164
=> [WFGP-180] During provisioning store jakarta transformed artifacts in a temp maven repo for reuse during example config generation

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Make sure the value of jboss-maven-dist is actually used.
=> [WFGP-181] jboss-maven-dist option value is ignored

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-187
=> [WFGP-187], Properly quote the file separator passed to String.replaceAll, continuing

pom.xml
Signed-off-by: Scott Marlow <smarlow@redhat.com>
=> Please upgrade to Batavia 1.0.3.final

maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleXmlVersionResolver.java
Issue: https://issues.redhat.com/browse/WFGP-189
=> [5.x] [WFGP-189] Throw an exception instead of logging a warning when artifacts cannot be resolved in module.xml

maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ModuleXmlVersionResolver.java
Issue: https://issues.redhat.com/browse/WFGP-189
=> [WFGP-189] Throw an exception instead of logging a warning when artifacts cannot be resolved in module.xml

config-gen/pom.xml, docs/guide/maven-plugins/index.adoc, docs/pom.xml, feature-spec-gen/pom.xml, galleon-plugins/pom.xml, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugin/pom.xml, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeatureSpecGeneratorInvoker.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, pom.xml, transformer/pom.xml, transformer/src/main/java/org/wildfly/galleon/plugin/transformer/BataviaTransformer.java, transformer/src/main/java/org/wildfly/galleon/plugin/transformer/JakartaTransformer.java, transformer/src/main/java/org/wildfly/galleon/plugin/transformer/JarUtils.java, transformer/src/main/java/org/wildfly/galleon/plugin/transformer/TransformedArtifact.java, transformer/src/main/java/org/wildfly/galleon/plugin/transformer/Utils.java
This PR merges 5.x into master.
Notes:
4.x branch is in sync with master branch.
5.x branch will be deleted.
=> Merged 5.x branch into master

maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java
Issue: https://issues.redhat.com/browse/WFGP-192
=> Fix for WFGP-192, Separate tools and core-tools when building FP

pom.xml
=> Upgrade Batavia to 1.0.6.Final

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/Utils.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/test/java/org/wildfly/galleon/plugin/UtilsTestCase.java
Issue: https://issues.redhat.com/browse/WFGP-194
=> Fix for WFGP-194, Add the ability to override artifacts during provisioning

pom.xml
Brings in fixes:
* [BATAVIA-101] Transform the legacy JAXB NS to the EE9
=> Upgrade Batavia to 1.0.8.Final

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractEE9ArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractModuleTemplateProcessor.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/EE9ArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/EE9ArtifactTransformerInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/FatModuleTemplateProcessor.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ModuleTemplate.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/SimpleArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ThinModuleTemplateProcessor.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
https://issues.redhat.com/browse/WFGP-200
https://issues.redhat.com/browse/WFGP-201
@bstansberry , a much cleaner implementation + some bug fixes that I discovered during rework.
=> WFGP-200 and WFGP-201, jakarta transformation rework and fix copied artifact transformation

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
When a feature-pack is built, create a new artifact (with "channel"
classifier" and "yaml" extension) that represents the channel definition
for the feature pack.
This feature is controlled by the generate-channel
parameter (optional, false  by default)
Dependencies to other feature-packs are defined in the channel's
"requires" field. They can be skipped if
add-feature-packs-as-required-channels is set to false (optional, true
by default).
JIRA: https://issues.redhat.com/browse/WFGP-222
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>
=> [WFGP-222] Generate YAML channel definition

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/BaseConfigGenerator.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/ForkedConfigGenerator.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigGenerator.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigsReader.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfEmbeddedTaskBase.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfProvisionedConfigHandler.java, feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ConfigGeneratorException.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ForkCallback.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ForkedEmbeddedUtil.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ForkedProcessRunner.java
Issue: https://issues.redhat.com/browse/WFGP-224
@jfdenise could you review? I tried to remove galleon core classes from code run in forked mode. Alternatively maybe it would be possible to change the class loader used by the forked mode.
=> [WFGP-224] Separating code needed to run forked WfConfigGenerator

pom.xml
JIRA: https://issues.redhat.com/browse/WFGP-228
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>
---
Dev tag: https://github.com/wildfly-extras/wildfly-channel/releases/tag/1.0.0.Alpha16
Diff to previous integrated release: https://github.com/wildfly-extras/wildfly-channel/compare/1.0.0.Alpha15...1.0.0.Alpha16
=> [WFGP-228] Upgrade wildfly-channel 1.0.0.Alpha16

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/JakartaTransformation.java
Issue: https://issues.redhat.com/browse/WFGP-229
=> Fix for WFGP-229, Exclude artifact from transformation using classifier

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/test/java/org/wildfly/galleon/maven/ChannelGenerationTestCase.java
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>
=> Add test for YAML Channel generation

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser33.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WildFlyFeaturePackBuild.java, pom.xml
Issue: https://issues.redhat.com/browse/WFGP-231
Requires Galleon update with https://github.com/wildfly/galleon/pull/309
=> [WFGP-231] Add system-paths option to wildfly-feature-pack-build

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ArtifactRecorder.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/SimpleArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-236
=> [WFGP-236] Record and cache resolved artifacts

maven-plugin/pom.xml, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/test/java/org/wildfly/galleon/maven/ChannelGenerationTestCase.java, pom.xml
Issue: https://issues.redhat.com/browse/WFGP-240
=> Fix for WFGP-240, Generate a channel manifest furing feature-pack build

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/BaseConfigGenerator.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Jira issue: https://issues.redhat.com/browse/WFGP-239
Build on top of #244
=> [WFGP-239] Resettable System Properties for embedded servers

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
Issue: https://issues.redhat.com/browse/WFGP-241
=> [WFGP-241] Expose generate-channel-manifest as system property

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-244
=> [WFGP-244] Cache wildfly-config-gen jar if needed

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java
Issue: https://issues.redhat.com/browse/WFGP-246
=> Fix WFGP-246, Snapshot company artifact not resolved after upgrade to Maven 3.9.0

docs/guide/intro/index.adoc
Issue: https://issues.redhat.com/browse/WFGP-242
=> Fix for WFGP-242, Documentation for WfInstallPlugin options

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractModuleTemplateProcessor.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ModuleTemplate.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-248
=> Fix for WFGP-248, Throw a better exception than an NPE when a dependency is missing in a feature pack

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/PropertyReplacer.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-249
=> Fix for WFGP-249, Versions in licenses are not correct when enabling Channels

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractModuleTemplateProcessor.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/FatModuleTemplateProcessor.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ThinModuleTemplateProcessor.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/Utils.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WildFlyChannelResolutionMode.java, galleon-plugins/src/test/java/org/wildfly/galleon/plugin/UtilsTestCase.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, pom.xml
Issue: https://issues.redhat.com/browse/WFGP-250
=> Fix for WFGP-250, Advertise WildFly Channel resolution when building/provisioning feature-pack

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ArtifactRecorder.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/test/java/org/wildfly/galleon/plugin/ArtifactRecorderTestCase.java
Issue: https://issues.redhat.com/browse/WFGP-255
=> [WFGP-255] Remove duplications from artifact cache generated during installation

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java
Issue: https://issues.redhat.com/browse/WFGP-258
=> Resolve plugins and config-gen before packages resolution

galleon-plugins/pom.xml, pom.xml
Issue: https://issues.redhat.com/browse/WFGP-261
Signed-off-by: Ruben Dario Novelli [rnovelli@redhat.com](mailto:rnovelli@redhat.com)
=> [WFGP-261] Upgrade to jandex 3.0.6

galleon-plugins/pom.xml, pom.xml
Issue: https://issues.redhat.com/browse/WFGP-261
Signed-off-by: Ruben Dario Novelli [rnovelli@redhat.com](mailto:rnovelli@redhat.com)
=> [6.4.x] [WFGP-261] Upgrade to jandex 3.0.6

.github/workflows/nightly-backward-30.yml, .github/workflows/nightly-backward-31.yml, .github/workflows/nightly-workflow.yml, .github/workflows/testing-workflow.yml
Issues:
* https://issues.redhat.com/browse/WFGP-268
* https://issues.redhat.com/browse/WFGP-271
The checks are expected to fail, the workflow files being not yet in main branch. Will re-run afterwards.
=> Fix for WFGP-271 and Fix for WFGP-268

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, pom.xml, testsuite/test-feature-packs/community-feature-pack/pom.xml, testsuite/test-feature-packs/default-feature-pack/pom.xml, testsuite/test-feature-packs/experimental-feature-pack/pom.xml, testsuite/test-feature-packs/preview-feature-pack/pom.xml, testsuite/tests/pom.xml, testsuite/tests/src/test/java/org/wildfly/galleon/plugins/test/FeaturePackContentTestCase.java
Issue: https://issues.redhat.com/browse/WFGP-274
=> Fix for WFGP-274, Introduce package and config stability

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, pom.xml
Issue: https://issues.redhat.com/browse/WFGP-280
=> WFGP-280, Finalize script execution is broken a when stability level is set

.github/workflows/nightly-backward-30.yml, .github/workflows/nightly-backward-31.yml, .github/workflows/nightly-workflow-older.yml, .github/workflows/nightly-workflow.yml, .github/workflows/testing-workflow.yml
Galleon plugins is no more compatible (removal of transformer), Glow gives different results.
=> Rework nightly backward compatibility CI

config-gen/pom.xml, docs/guide/examples/user-defined-feature-pack/content.adoc, docs/guide/maven-plugins/index.adoc, docs/guide/maven-plugins/wildfly-feature-pack-build-xml/index.adoc, docs/pom.xml, feature-spec-gen/pom.xml, galleon-plugins/pom.xml, maven-plugin/pom.xml, maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/FeaturePackBuildModelParser34.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/UserFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WildFlyFeaturePackBuild.java, maven-plugin/src/test/java/org/wildfly/galleon/maven/StabilityOptionsTestCase.java, pom.xml, testsuite/pom.xml, testsuite/test-feature-packs/common/pom.xml, testsuite/test-feature-packs/community-feature-pack/pom.xml, testsuite/test-feature-packs/default-feature-pack/pom.xml, testsuite/test-feature-packs/experimental-feature-pack/pom.xml, testsuite/test-feature-packs/pom.xml, testsuite/test-feature-packs/preview-feature-pack/pom.xml, testsuite/test-feature-packs/subsystem-community/pom.xml, testsuite/test-feature-packs/subsystem-default/pom.xml, testsuite/test-feature-packs/subsystem-experimental/pom.xml, testsuite/test-feature-packs/subsystem-preview/pom.xml, testsuite/tests/pom.xml
* Move the version to 7.1.0.Final-SNAPSHOT
* Fix for: https://issues.redhat.com/browse/WFGP-281
* Fix for: https://issues.redhat.com/browse/WFGP-275
=> Fix for WFGP-275 and WFGP-281

maven-plugin/src/main/java/org/wildfly/galleon/maven/AbstractFeaturePackBuildMojo.java, maven-plugin/src/test/java/org/wildfly/galleon/maven/StabilityLevelTestCase.java, pom.xml, testsuite/test-feature-packs/common/src/main/resources/configs/standalone/model.xml, testsuite/test-feature-packs/common/src/main/resources/layers/standalone/test-layer-default/layer-spec.xml
Issue: https://issues.redhat.com/browse/WFGP-282
=> Fix for WFGP-282, Ignore package dependency with attached stability when building feature-pack

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ArtifactRecorder.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ShadedModel.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/SimpleArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/Utils.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/AssembleShadedArtifact.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser32.java, galleon-plugins/src/test/java/org/wildfly/galleon/plugin/ArtifactRecorderTestCase.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenProjectArtifactVersions.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ShadedJARModelGeneratorMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, maven-plugin/src/main/resources/schema/wildfly-feature-pack-tasks-3_2.xsd, maven-plugin/src/test/java/org/wildfly/galleon/maven/ShadedJARModelGeneratorTestCase.java, maven-plugin/src/test/java/org/wildfly/galleon/maven/build/xml/TasksTestCase.java, maven-plugin/src/test/resources/xml/tasks.xml
Issue: https://issues.redhat.com/browse/WFGP-286
=> [Main] Fix for WFGP-286, Shaded jar handling

.github/workflows/ci.yml, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/AbstractArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ArtifactRecorder.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/ShadedModel.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/SimpleArtifactInstaller.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/Utils.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfConstants.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/WfInstallPlugin.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/AssembleShadedArtifact.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser32.java, galleon-plugins/src/test/java/org/wildfly/galleon/plugin/ArtifactRecorderTestCase.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/MavenProjectArtifactVersions.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/ShadedJARModelGeneratorMojo.java, maven-plugin/src/main/java/org/wildfly/galleon/maven/WfFeaturePackBuildMojo.java, maven-plugin/src/main/resources/schema/wildfly-feature-pack-tasks-3_2.xsd, maven-plugin/src/test/java/org/wildfly/galleon/maven/ShadedJARModelGeneratorTestCase.java, maven-plugin/src/test/java/org/wildfly/galleon/maven/build/xml/TasksTestCase.java, maven-plugin/src/test/resources/xml/tasks.xml
Issue: https://issues.redhat.com/browse/WFGP-287
=> [6.4.x] Fix for WFGP-287, Shaded JAR Handling

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/ServerBridge.java
Issue: https://issues.redhat.com/browse/WFGP-288
=> Fix for WFGP-288, Class cast exception when error occurs during provisioning

maven-plugin/src/test/java/org/wildfly/galleon/maven/FeaturePackBuildModelParserTestCase.java, maven-plugin/src/test/resources/xml/test-feature-pack-build.xml
Issue: https://issues.redhat.com/browse/WFGP-270
=> Fix for WFGP-270, Add testing of FeaturePackBuildModelParser

galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ForkedEmbeddedUtil.java, galleon-plugins/src/test/java/org/wildfly/galleon/plugin/server/ForkedEmbeddedUtilTestCase.java
Issue: https://issues.redhat.com/browse/WFGP-294
=> Fix for WFGP-294, Invalid Exception parsing in forked process mode

config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfConfigGenerator.java, config-gen/src/main/java/org/wildfly/galleon/plugin/config/generator/WfEmbeddedTaskBase.java, feature-spec-gen/src/main/java/org/wildfly/galleon/plugin/featurespec/generator/FeatureSpecGenerator.java, galleon-plugins/src/main/java/org/wildfly/galleon/plugin/server/ForkedEmbeddedUtil.java
Issue: https://issues.redhat.com/browse/WFGP-295
=> Fix for WFGP-295, Forked server output should be printed if exception parsing fails or when debug is enabled
